apiVersion : apps/v1
kind: Deployment
metadata:
  name: "authkcn-8734"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "authkcn-8734"
  template:
    metadata:
      labels:
        app: "authkcn-8734"
    spec:
      containers:
        - name: "authkcn-8734"
          image: "authcr123.azurecr.io/authkcn"
          ports:
          - containerPort: 80