apiVersion: v1
kind: Service
metadata:
    name: "authkcn-3222"
    labels:
        app: "authkcn-3222"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "authkcn-3222"