on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: authcr123.azurecr.io
        username: ${{ secrets.acr_authcr123_username }}
        password: ${{ secrets.acr_authcr123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t authcr123.azurecr.io/authkcn:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push authcr123.azurecr.io/authkcn:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_authkcn_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep authkcnb039 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace authkcnb039`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: authkcnb039
        container-registry-url: authcr123.azurecr.io
        container-registry-username: ${{ secrets.acr_authcr123_username }}
        container-registry-password: ${{ secrets.acr_authcr123_password }}
        secret-name: authkcndockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: authkcnb039
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          authcr123.azurecr.io/authkcn:${{ github.sha }}
        imagepullsecrets: |
          authkcndockerauth
